name: Deploy to GithubPages

on: pull_request
permissions:
  contents: write
jobs:
  deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Packages
        run: |
          npm ci

      - name: Build prod
        run: |
          npm run build
          cp dist/index.html dist/404.html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
