name: Lint and Test

on: pull_request
permissions:
  contents: write
jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Packages
        run: |
          npm ci

      - name: Lint
        run: npm run lint

      - name: Type-check
        run: npm run type-check

